### ISSUE TITLE
TW_INCLUDE_FASTBOOTD

### ISSUE THREAD

**Issue by lopestom** [ManInTheMirrow/android_device_bqru_BQru-5745L#2]
I read about your doubt but I not know if you solved
TW_INCLUDE_FASTBOOTD := true

For have fastbootd working need more binaries/packages like you put or create a new file called `device.mk` and writing:
```
# Fastbootd
PRODUCT_PACKAGES += \
    android.hardware.fastboot@1.0-impl-mock \
    android.hardware.fastboot@1.0-impl-mock.recovery \
    fastbootd
```

For know if fastbootd working write with adb-fastboot:
`fastboot getvar is-userspace`

![fastbootd](https://github.com/lopestom/android_device_bqru_BQru-5745L/releases/download/test/IMG_20220621_233157_713.4.jpg)

Obviously whether fastbootd is still not working (no) depends on the configuration, drivers and correct addressing in the usb.rc file

Looking usb.rc files your device has: https://github.com/ManInTheMirrow/android_device_bqru_BQru-5745L/blob/262a2b9e6cdde4fe98d5e012d68f3304280f341c/recovery/root/init.recovery.common.rc#L119-L128
https://github.com/ManInTheMirrow/android_device_bqru_BQru-5745L/blob/262a2b9e6cdde4fe98d5e012d68f3304280f341c/recovery/root/init.recovery.common.rc#L130
https://github.com/ManInTheMirrow/android_device_bqru_BQru-5745L/blob/262a2b9e6cdde4fe98d5e012d68f3304280f341c/recovery/root/init.recovery.common.rc#L139

Maybe the names and PID/VID cause conflict?!

**Comment by ManInTheMirrow** [comment]
> For have fastbootd working need more binaries/packages

Thanks for your message, I will try to add the missing packages.

**Comment by ManInTheMirrow** [comment]
Hi!
Thanks for your advice.
No, I have not been able to solve the problem of running fastbootd. I added
missing binary files and changed init.usb.rc many times, but it did not
give any result. I don't know what else I can change in the sources to make
fastbootd work. Maybe it's because I have a 32 bit system. Sorry it took me
a long time to reply to you.

пт, 25 авг. 2023 г. в 17:18, lopestorm ***@***.***>:

**Comment by lopestom** [comment]
Okay. I remembered about some tool for Samis devices and your Issue.
I not know if this solve the Issue or work with SPD devices. But you can try and write feedback about this.
https://github.com/ChonDoit/Patch-Recovery

https://github.com/ChonDoit/Patch-Recovery#how-to-use
